### ISSUE TITLE
No hello on screen

### ISSUE THREAD

**Issue by digitongithub** [wegi1/ESP32-8048S070-7INCH-LCD#2]
I've been trying for a while to get my esp32s3-8048S070 up and running with the latest new IDE.
I have followed exactly the manual of the ESP32-8048S070-7INCH-LCD-main but keep having constant errors.

Compilation error: 'Arduino_ESP32RGBPanel' does not name a type; did you mean 'Arduino_ESP32S2PAR8Q'?

How can i work this display?

**Comment by wegi1** [comment]
I can't compile it on Arduino framework. This never work for me in the Arduino IDE. I got the working demo here:
https://github.com/wegi1/ESP32_S3_7INCH_LVGL_DEMO

BUT... it work under Visual Studio Code in PlatformIO Arduino framework.

I can recommended for you migration to VSC PlatformIO

**Comment by digitongithub** [comment]
Thanks. I only use arduino, so i must see how to work with Visual Studio
